auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: ThinkingYu.com
url: http://www.thinkingyu.com
feed: /atom.xml
author_info: <a href="www.thinkingyu.com/">ThinkingYu</a>
